# Site settings
title: Razvan Balosin
email: contact@razvanbalosin.com
description: > # this means to ignore newlines until "baseurl:"
  Front End Engineer with a passion for JavaScript, AngularJS and HTML5
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://razvanbalosin.com" # the base hostname & protocol for your site
twitter_username: razvanbalosin
github_username:  razvanbalosin

# Build settings
markdown: kramdown
paginate: 2
paginate_path: "/page:num/"
sass:
    style: :compressed
